spring.application.name=ConferenceManagement

# Database connection details
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Testing@123

# Optional: specify the driver class name (often auto-detected)
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Hibernate JPA settings for schema management (use with caution in production)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
